---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: devops-tool
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
         app: kibana
  spec:
    containers:
    - name: kibana
      image: kibana:latest
      resources:
        limits:
          cpu: 1000m
        requests:
          cpu: 100m
      env:
      - name: ELASTICSEARCH_URL
        value: http://54.180.183.17:30560
      - name: SERVER_BASEPATH
        value: /api/v1/namespaces/kube-system/services/kibana-logging/proxy
      ports:
      - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    name: http
    nodePort: 30561
  selector:
    app: kibana
  type: LoadBalancer
---