# Generated by Django 3.1.7 on 2021-06-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일')),
                ('user_index', models.AutoField(primary_key=True, serialize=False, verbose_name='회원번호')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('birth_day', models.CharField(blank=True, max_length=10, null=True)),
                ('pwd_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '유저',
                'db_table': 'user',
            },
        ),
    ]
