# Generated by Django 3.1.7 on 2021-03-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_index', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pwd', models.CharField(max_length=50)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(max_length=50)),
                ('auth_code', models.CharField(blank=True, max_length=20, null=True)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('birth_day', models.CharField(blank=True, max_length=10, null=True)),
                ('pwd_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
